### ISSUE TITLE
Improve visibility and use of the dispute process

### ISSUE THREAD

**Issue by wheresrhys** [npm/policies#41]
I recently came across your dispute policy for the first time, and have to compliment its clarity. However, there are a few times in the past when this would have been very useful to myself and the projects I've worked on. e.g. [This PR](https://github.com/substack/node-falafel/pull/24) to fix a bug which was breaking `npm shrinkwrap` (therefore having repercussions way beyond the scope of the package itself) was ignored for a year and a half.

I work at an organisation with many well informed node developers, but as far as I can tell nobody was aware of either the existence or scope of your dispute policy. Looking at the PR I referenced above - as well as other similar issues on poorly maintained repos - it's clear from the number of :+1:s that the dispute policy, and its applicability to the case of poorly maintained repos, is not widely known.

Can more be done to improve the community's knowledge and use of the dispute policy. e.g.
- A link on the repo's npm page saying 'report this package as abandoned/unmaintained'
- Some kind of integration with github issues that flags repos that have a lot of long-standing PRs/poor issue resolution rate

As an addendum to the above, IMHO one failing of the dispute process is that, for the case of poorly maintained repos, wanting to raise a dispute does not equate to wanting to or being qualified to take ownership (e.g, in the PR I posted above the fix was a tiny tweak to the package.json). Perhaps it'd be a good idea to establish a community maintainers group that ownership of abandoned repos can be transferred to.

**Comment by ashleygwilliams** [comment]
hey @wheresrhys this is a really excellent idea. we've been swamped with community response, but i really appreciate how constructive and thoughtful this idea is. i will bring this up with the team and get back to you! thanks for contributing!

**Comment by kemitchell** [comment]
@wheresrhys, this issue has been open and idle for a while, so I am closing it.

Our [dispute policy](https://www.npmjs.com/policies/disputes) has continued to evolve since this issue opened, and I'm sure we'll continue to refine it.

I wasn't part of the particular conversations @ashleygwilliams had within npm, Inc. about your ideas. But npmjs.com has had many changes in the general direction, including interface improvements and an overhaul to search that takes account of maintainership metrics. At the same time, I don't believe there have been any fundamental changes to our approach on name disputes.
