### ISSUE TITLE
Question: Are there plans to require legal action before giving up package name ownership?

### ISSUE THREAD

**Issue by fearphage** [npm/policies#46]
During left pad gate, NPM changed ownership of a package name based on a few emails. In the [blog post](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm), it was highlighted that it was not a legal issue. I would expect something of this magnitude to require a cease and desist letter or some other legal action prior to ownership being changed to a new party.

Do you plan on requiring legal action in the future or will a few emails continue to be all it takes to relinquish a user's package name?

**Comment by ashleygwilliams** [comment]
hi! we don't intend on formally requiring it, but functionally, yes, we will require significantly more, and more serious, action be taken before we change ownership of a package.

**Comment by ashleygwilliams** [comment]
you're welcome!

**Comment by fearphage** [comment]
Follow up question - What is the benefit (to NPM and the end users) to making it essentially best practice over documented requirements/rules?

**Comment by ashleygwilliams** [comment]
that's a good question, @fearphage. it's because right now we don't have enough data to be able to state exactly what the best plan of action would be in a whole ton of often very different, specific cases. the combination of how surprisingly unique most of these situations are, combined with our lack of real data on how frequently these cases occur and the affect on the community, make it clear to us that the smart move is to start collecting that data, and follow a best practices approach until the cowpaths emerge.
